name: scholarar
description: "A Passenger app use for booking a ride"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  modal_progress_hud_nsn: ^0.5.1
  connectivity: ^3.0.3
  get: any
  get_it: ^7.6.4
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^9.0.0
  http: any
  dio: ^5.2.0
  pin_code_fields: ^8.0.1
  camera: ^0.10.2
  image: ^4.1.5
  image_picker: ^1.0.7
  image_gallery_saver: ^2.0.3
  cached_network_image: ^3.2.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  scan: ^1.6.0
  flutter_app_badger: ^1.5.0
  permission_handler: ^11.3.0
  path_provider: ^2.0.15
  clipboard: ^0.1.3
  share_plus: ^8.0.2
  encrypt: ^5.0.1
  package_info_plus: any
  url_launcher: ^6.0.10
  firebase_app_installations: ^0.2.2+1
  fluttertoast: ^8.0.9
  shimmer: ^3.0.0
  device_info_plus: ^10.0.1
  path: any
  http_parser: any
  country_phone_code_picker: ^0.0.43
  scroll_to_index: ^3.0.1
  rect_getter: ^1.0.0
  flutter_pw_validator: ^1.6.0
  carousel_slider: ^4.2.1
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.1.0
  smooth_page_indicator: ^1.1.0
  #google_fonts: ^6.2.1
  pod_player: ^0.2.1
  flutter_spinkit: ^5.2.1
  html: ^0.15.4
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.10
  flutter_polyline_points: ^2.1.0
  flutter_paypal_payment: ^1.0.6
  flutter_inappwebview: ^5.8.0
#  location: ^6.0.2
  flutter_phone_direct_caller: ^2.1.1
  google_fonts: ^6.2.1
  curved_drawer_fork: ^0.0.1+1
  csc_picker: ^0.2.7
  #firbase
  firebase_core: ^2.3.0
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  flutter_local_notifications: ^17.2.1
  #firebase_app_installations: ^0.2.5+7
  firebase_messaging: ^14.9.4
  flutter_launcher_icons: ^0.13.1
  flutter_geofire: ^2.0.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.jpg"

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/languages/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/ArimaKoshi-Regular.otf
          weight: 400


